### ISSUE TITLE
New TestRail API breaks get_tests() in publish_results

### ISSUE THREAD

**Issue by steverawlins-zebra** [ATEME/robotframework-testrail#12]
[TestRail 7.2.1 release](https://discuss.gurock.com/t/bulk-api-endpoint-changes-coming-soon/19537) now mandates paging on get-tests API with no backwards-compatibility option.

As currently coded, this API change causes a "string indices must be integers" TypeError when fetching the list of test-cases for a given Report:

+ python /rf_2_tr/robotframework2testrail.py --tr-config=**** --tr-run-id=3036 /home/jenkins/agent/workspace/Robot_Tests_-_Daily_develop/test-output/user-management_TestSuite_Workspace_Service.xml
Publish in Test Run #3036
Traceback (most recent call last):
  File "/rf_2_tr/robotframework2testrail.py", line 285, in <module>
    if publish_results(
  File "/rf_2_tr/robotframework2testrail.py", line 126, in publish_results
    case_id_in_testrun_list = [str(tc['case_id']) for tc in testcases_in_testrun_list]
  File "/rf_2_tr/robotframework2testrail.py", line 126, in <listcomp>
    case_id_in_testrun_list = [str(tc['case_id']) for tc in testcases_in_testrun_list]
TypeError: string indices must be integers

**Comment by anitagaga** [comment]
I am having the same issue. Does anybody knows the solution?

**Comment by steverawlins-zebra** [comment]
Yes.  ["Seppo" from Finland provided a nice solution which works for me](https://discuss.gurock.com/t/getcases-api-cannot-understand-iterating-jarray-noob-question/19639/8).  Let me link it to you.

**Comment by steverawlins-zebra** [comment]
Here it is, in the form of PR to this very project.  All credit to the author.  I tested it and it solved our upload-to-TestRail problem:

https://github.com/ATEME/robotframework-testrail/pull/11

**Comment by anitagaga** [comment]
thank you so much! it works now!

**Comment by hernandikrammes** [comment]
I'm blocked by this issue, how should I proceed to fix it?
